## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:
  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  config:
    url: https://52.79.92.32:8081
    dex.config: |
      logger:
        level: debug
        format: json
      connectors:
      - type: saml
        id: okta
        name: Okta
        config:
          ssoURL: https://trial-3450531.okta.com/app/trial-3450531_argocdsaml_1/exkssp056aFjjBTxD697/sso/saml
          caData: | 
            LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxakNDQXBLZ0F3SUJBZ0lHQVpmQVRob0JNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1ZNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcKQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHQTFVRUNnd0VUMnQwWVRFVQpNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RmpBVUJnTlZCQU1NRFhSeWFXRnNMVE0wTlRBMU16RXhIREFhQmdrcWhraUc5dzBCCkNRRVdEV2x1Wm05QWIydDBZUzVqYjIwd0hoY05NalV3TmpNd01UQXdOakV6V2hjTk16VXdOak13TVRBd056RXpXakNCbFRFTE1Ba0cKQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG1iM0p1YVdFeEZqQVVCZ05WQkFjTURWTmhiaUJHY21GdVkybHpZMjh4RFRBTApCZ05WQkFvTUJFOXJkR0V4RkRBU0JnTlZCQXNNQzFOVFQxQnliM1pwWkdWeU1SWXdGQVlEVlFRRERBMTBjbWxoYkMwek5EVXdOVE14Ck1Sd3dHZ1lKS29aSWh2Y05BUWtCRmcxcGJtWnZRRzlyZEdFdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFwcWhtKzBnblptTXdKclJKb2VFQXVCWVI0SWFTbExTY1RENzZIcGZ4NFhlcGIrTTR6M1hqWkhlWDNxcnBwMXJ2dTNqRAp3QnVYNlFTRTJJQm9WdDFpWGpROXJsdXFCUG9SWU1tRjRjVVNvanVkMkJxL3Q1OUU1Z3ZHSWluVW1TT3J4QkIzemVvWHFoMXhCWnd6CmpVN3BFeTNBcklreUJ5TlgrelA1WmVrYmY2Q3BtVGZEdFBtYWdaSHdmNWJPSXluSCtQM1g1d05XSEZPV0xqS3M4aE83TWZ3QkVyaVcKTERGaFNmaTVWN09PVU5vNzFKV0laUUxZbUt2UEQzcDBWN3plcHhVY292WkJOMUFuUlpkUHJ4UVpCa3ZUSkVuSWs2eUV0T0VuK2VsRQpEamFDdVZqcXpINDc1TjloNldSK1dsNFVWdjJTbUpmRWI5MzNEQnEwaDhrcFJ3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQnpHMjFMWDBIQy8vT1FjZlhISDRZcVZLZlBKd1JNSjVQN1VucnFFVEt4ZjZPVFk1VGFwL2JlLzZObWZuc0RFNURLaGIvNEI0c04KREszbndpWXVZb1MrQURTdzNxaVBISzI0UktGbHVUZTc4SEltMmphMkJJNG5URmIvZngrSWVvSDJIUXc3bC9Tckd6cDIwcGlhWG1lUgpDU01PTDl6QjFVZXlXdUhrVm1qa1FyNm00RVdhRUw5U2RBa2NyRzR2MHZsS3kzNkpkc1g3V2g5QW1LdHVpMTJ2cFdsTEhkT0lqaHM4CmdOaHdDY3UvRG5RUFBEWWtUbjU2clk1d1Z5anU0cWRCSEdKQTlBaHBrQ0FKajhhVmM4OFJYSmsyL0t5SGZmWDFqU1cxOHNHREFDTUEKbUExN1FNK3c3a292ckNZMmtPVDlmUWVsdS9ENG5iWko5UE1OdGUxeAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          #ca: /path/to/ca.pem
          redirectURI: http://54.180.243.148:8081/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: group
    repositories: |
      - type: git
        url: https://github.com/dzungda/argocd.git
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
  additionalApplications: 
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../values-override.yaml
        path: argocd-install/argo-cd
        repoURL: https://github.com/dzungda/argocd.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
    - name: argocd-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-apps
        repoURL: https://github.com/dzungda/argocd.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: argocd-appprojects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-appprojects
        repoURL: https://github.com/dzungda/argocd.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
  additionalProjects: 
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
