apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: sample-app
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  project: default
  #sample-project
  source:
    path: deployment/bookinfo
    repoURL: https://github.com/dzungda/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
