apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: nginx  
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: dungda7/app-demo
    argocd-image-updater.argoproj.io/write-back-method: git
spec:  
  project: sample-project
  source:  
    repoURL: https://github.com/dzungda/argocd.git 
    path: deployment/nginx
    targetRevision: HEAD 
  destination:  
    server: https://kubernetes.default.svc  
    namespace: sample-app 
  syncPolicy:  
    automated: {} 
