apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: nginx  
  namespace: sample-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: dungda7/app-demo
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:  
    server: https://kubernetes.default.svc  
    namespace: sample-app 
  project: sample-project
  source:  
    repoURL: https://github.com/dzungda/argocd.git 
    path: deployment/nginx
    targetRevision: HEAD 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
