apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    - path: sample-app/bookinfo
      repoURL: https://github.com/dzungda/argocd.git
      targetRevision: HEAD
    - path: sample-app/nginx
      repoURL: https://github.com/dzungda/argocd.git
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
