apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
